### PR TITLE
Added username and corrected a few typos

### PR DESCRIPTION
**Pull request by JonArnfred**

### CODE REVIEW

**Comment by AndersHqst** [comment]
Good stuff, thanks!

**Comment by hulvei3** [comment]
Hi @JonArnfred, and thank you for signing up.
Please state your email in a comment or send it to mha@e-conomic.com

**Comment by JonArnfred** [comment]
email is jonarnfred@gmail.com

**Comment by hulvei3** [comment]
thank you

Med venlig hilsen / Best regards

Morten Hulvej Andersen
Software Engineer

[cid:E62C9195-891D-43F0-8260-91290A4A66EA]
e-conomic international a/s · www.e-conomic.dkhttp://www.e-conomic.dk/ · Langebrogade 1 · DK-1411 København K
mha@e-conomic.commailto:mha@e-conomic.com  · Phone: +45 8820 4840

Den 15. jan. 2016 kl. 10.05 skrev JonArnfred <notifications@github.com<mailto:notifications@github.com>>:

email is jonarnfred@gmail.commailto:jonarnfred@gmail.com

**Pull request merged**
