### PR TITLE
Memphis week3 ass4

### PR DESCRIPTION
**Pull request by memphis88**

### CODE REVIEW

**Comment by hulvei3** [comment]
You still have code inside your html.
Update: okay, that was ass3. - You don't really need that change in here. Remember to keep your PRs clean!

**Comment by hulvei3** [comment]
Avoid using upper-case file names. Separate by `message-list.jsx` instead.

**Comment by hulvei3** [comment]
Works fine - great job

**Comment by memphis88** [comment]
I expected that assignment 3 did not belong in the PR but it happened for 2 reasons:
- When I made the branch, assignment 3 was not ready so it did not exist in master branch (which is the parent branch)
- When I copied the file from the master branch (checkout), it was automatically staged so it was already late when I noticed that it was pushed on github.

To avoid future issues with this, what would be the best action to take in a similar situation? Un-stage the file before committing? Or relying on github for viewing other versions of code? Also, is there anything I can do to fix the PR now? I assume that deleting the file will also delete it from master when merged.

As for the naming of files, is the guideline a matter of convention to avoid confusion between variables and files or is there any other more specific reason?

Changing the file names and pushing soon.

Edit: I also noticed from @calinilie 's comments that bundle.js and generated files should not be included in the repo, which makes a lot of sense. Should I untrack it?

**Comment by hulvei3** [comment]
Yes, you should remove `bundle.js` from git - didn't see that.

For the branch you can just remove `week2/ass3/index.html`. The diff you see here is towards master and shows it as a new file. So removing it shouldn't delete anything but you can always show the diff locally by `git diff master`

**Comment by memphis88** [comment]
Okay, I think it looks better now!

**Comment by hulvei3** [comment]
yes, it is. When looking at the full change only week3 stuff is added.

**Pull request merged**
