### PR TITLE
Benny week4 ass5

### PR DESCRIPTION
**Pull request by DenLilleMand**

### CODE REVIEW

**Comment by DenLilleMand** [comment]
Cool way to create ids

``` javascript
function generateId() {
    if (_lists.length == 0) {
        return 1;
    } else {
        var ids = _lists.map(l => l.id);
        return Math.max(...ids) + 1;
    }
}

```

**Comment by ghost** [comment]
Gooogle is my freind :-)

**Comment by DenLilleMand** [comment]
the action being returned from a action creator, can have a variable structure, obviously, the standard is just it having some payload and type, but i think its kind of nice to nest the data in a  payload/data key, so the structure of the action is not polluted. 

``` javascript
    createList: function(listName) {
        AppDispatcher.dispatch({
            type: Constants.CREATE_LIST,
            listName: listName,
        });
    },
```

If we had to extend the action object later:

``` javascript
createList: function(listName) {
    AppDispatcher.dispatch({
        type: Constants.CREATE_LIST,
        payload: {
            listName: listName,
        },
        localization: {

        },
        logging: {

        },
        ...crossCuttingConcerns
    });
},
```

**Comment by DenLilleMand** [comment]
I think its nice that you adhere to the naming convention of "private" functions using underscore

``` javascript
    _onChange: function() {
         this.setState(getAppState());
    },

```

**Comment by DenLilleMand** [comment]
in Package.json Replace:

``` javascript
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack"
  },
```

With:

``` javascript
    "scripts": {
     "test": "echo \"Error: no test specified\" && exit 1",
     "build": "webpack -d --progress --colors --watch",
     "production": "webpack -p"
   },
```

-d puts it in development mode, so it generates sourcemaps, so that errors in the console actually points to the file you had before the transpilation from es6 -> es5.   --progress just shows some percentages while building, --colors gives colors!,  and --watch is def the most important of the features, it will watch all of the files in your project and when you change them it will build it automatically in a clever way, so it only just changes that little bit , instead of rebuilding the entire thing from scratch as you do it now.

**Comment by DenLilleMand** [comment]
In package.json you have the following key:

``` javascript
  "devDependencies": {
    "babel-core": "^6.5.2",
    "babel-loader": "^6.2.3",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "webpack": "1.12.13",
    "flux": "^2.1.1",
    "events": "^1.1.0"
  }
```

Im guilty of this my self, but all of those should probably just be added to the regular dependency key, like so:

``` javascript
  "dependencies": {
    "babel-core": "^6.5.2",
    "babel-loader": "^6.2.3",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "webpack": "1.12.13",
    "flux": "^2.1.1",
    "events": "^1.1.0"
  }
```

One of the differences is that when you clone the project into production, you can do a `npm install --production`    which won't install devDependencies. so if the server had babel globally installed or smt, then it would be better to put those into the devDependencies. anyway  ...

**Comment by DenLilleMand** [comment]
You give the key in as a prop, but never use it in message, probably because you figuired out that its a pretty bad idea to use the index of an array as a unique identifier accross the entire application, but anyway, it should be removed i guess. 

``` javascript
        var activeMessageList = this.props.messages.filter(e => !e.isArchived).map((message, index) => {
            return <Message key={index} 
                            message={message} />
        });
        var archivedMessageList = this.props.messages.filter(e => e.isArchived).map((message, index) => {
            return <Message key={index} 
                            message={message} />
        });
```

And another side note to keys is that in your message.js, you do:

``` javascript
        var otherLists = ListStore.getAll().filter(l => l.id != this.props.message.list).map((list, index) => {
            return <option key={list.id} value={list.id}>{list.name}</option>
        });
```

Have to consider how good a unique key is, only dependent on a list.id, so an idea would be to 
prefix the `list.id` with something domain specific enough to make it unique.

**Comment by DenLilleMand** [comment]
You haven't written the code yourself (in base.js):

``` javascript
var CHANGE_EVENT = 'change';
```

But i think it can be discussed whether or not its a good idea to assign a lowercase string to a variable with a name that surgests that the string value looks similar, as in : 

``` javascript
const CHANGE_EVENT = 'CHANGE_EVENT'; 
```

in this case maybe, we should look at the implementation of the onChange listener in the store, maybe it doesn't care about upper or lower case, and then we could do:

``` javascript
const CHANGE = 'CHANGE';
```

**Comment by DenLilleMand** [comment]
In list-store.js

``` javascript
AppDispatcher.register(payload => {

});
```

Maybe it should be named a action instead of payload.

**Comment by DenLilleMand** [comment]
in message-store:

``` javascript
var ListStore = require("../Stores/list-store");
var ListActions = require("../Actions/list-actions");
```

Two variables that aren't used, im thinking that they should be deleted, i guess youre not using them because it doesn't make sense that the store knows about the listactions.

**Comment by DenLilleMand** [comment]
Naming in the project files would probably make more sense if it was not a mix of camelcase and dashes.

**Comment by DenLilleMand** [comment]
crazy syntax:

``` javascript
                {!this.state.newListVisible &&
                    <div>
                        <button onClick={this.handleCommit}>Commit</button>
                    </div>}
```

**Comment by DenLilleMand** [comment]
I think you should consider the following implementation:

``` javascript
    CREATE_LIST: 'CREATE_LIST',

    CREATE_MESSAGE: 'CREATE_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    MOVE_MESSAGE: 'MOVE_MESSAGE',
    TOGGLE_IS_ARCHIVED: 'TOGGLE_IS_ARCHIVED',
```

I had a project with 8 files for different constants, and the actioncreators and stores had to import them,  and it becomes a hazzle really quickly, and its too much boilerplate and too much navigation between files. I think putting the constants together with the store that uses the constant and export it from there is the best idea. Then the actioncreator can import it from the store and use it. The only case where it might cause problems, is whenever several store uses a constant, then i would say that you'd need to decide which store owns the constant the most or seperate it into a seperate file. I allso like the idea of having a model that is pretty selfcontained and doesn't import stuff from the same files as a actioncreator, but maybe thats just MVC getting to me.

**Comment by DenLilleMand** [comment]
I think requireing a list store, in a inputfield component might make it difficult to follow the logic of the application. Later when we discuss clever and stupid components, this will become a huge no-go(i think) ... I think that the small components all know about the actioncreators, as they do right now in our applications is allready right at the edge of what is allowed - i like that idea though. But i really do think that we should still use reacts data flow, where a component at the top receives the data updates and passes it down to the children. 

 Allso you have to consider the flow that are allready there, your render method is being executed because props are being passed to the component right, but then in the render method you retrieve some additional data, i wonder why you couldn't just get it passed in together with the other props, this way you have two data sources, when the data comes from the same store. 

``` javascript
var ListStore = require("../Stores/list-store");

var lists = ListStore.getAll().map((list, index) => {
       return <option key={list.id} value={list.id}>{list.name}</option>
 });        
```

**Comment by DenLilleMand** [comment]
I think the data model is really interesting, ive never seen people basically copy a SQL schema as datastructure and present it as basically the only way to do it, as in the course right now. Until now, when ive received data on the client its often been from a ORM system else ive nested the structure my self, anyhow usually ending up in our case with an array of lists, inside of those lists we have the messages as objects or whatever.  It would be interesting to see a pro/con of these two methods, and what your backend technologies would look like to use something like this, because i imagine it wouldn't be ORM based(which alot of backends are, nowadays i guess)

**Comment by DenLilleMand** [comment]
Okay. I think that was basically what i had to say... I think overall the logic of the code is pretty easy to follow, and are nicely written and formulated. I think all the stuff i found was mostly just nitpicking, which this is all about i guess  :+1:

**Comment by hulvei3** [comment]
@DenLilleMand @BennyTordrupVisma feel free to continue the discussion or merge it yourself

**Comment by ghost** [comment]
Your comment on the key property on the message lists in list.js. The key is needed - otherwise, I get a warning in Chrome console:

Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `exports`. See https://fb.me/react-warning-keys for more information.

Replaced it to use the message.id as key instead - it will be unique inside the message array at any time.

**Comment by ghost** [comment]
I see your point in the payload structure.

**Comment by ghost** [comment]
I have implemented some of the suggested fixes in the next assignment and will merge this in as is.

**Pull request merged**
